@startuml

object Kunde


object Sælger


object Materialer


object Ordre {

}

object Tilbud {

}
object Bestilling {

}


object Carport


object Skur


object Stykliste

object StyklisteLinje

Stykliste "1" -- "1" Bestilling

Stykliste "1" -- "*" StyklisteLinje
Materialer "1" - "*" StyklisteLinje

Bestilling "*" -- "1" Kunde

Bestilling "1" -- "0..1" Tilbud
Tilbud "1" -- "0..1" Ordre

Carport "1" -- "1" Bestilling

Sælger "1" -- "*" Bestilling
Skur "0..1" -- "1" Carport
@enduml
